# Generated by Django 4.2.3 on 2023-07-30 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.CharField(max_length=20)),
                ('percent_change_1hr', models.CharField(max_length=10)),
                ('percent_change_24hr', models.CharField(max_length=10)),
                ('percent_change_7d', models.CharField(max_length=10)),
                ('market_cap', models.CharField(max_length=30)),
                ('volume_24h', models.CharField(max_length=30)),
                ('current_supply', models.CharField(max_length=20)),
            ],
        ),
        migrations.DeleteModel(
            name='Food',
        ),
    ]
