# Generated by Django 4.2.3 on 2023-07-30 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_stock_stock_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='current_supply',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='stock',
            name='market_cap',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='stock',
            name='volume_24h',
            field=models.CharField(max_length=100),
        ),
    ]
